---
language: python
python: 2.7
sudo: required

before_install:
  - sudo apt-get update -qq

install:
  - pip install ansible

script:
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

  - ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo

  - >
    ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
    | grep -q 'changed=1.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
